### ISSUE TITLE
Issue with Alfheim

### ISSUE THREAD

**Issue by SfortzaPhantom** [Draco18s/Artifacts#24]
Heyyah! This mod is pretty amazing (never saw such mods on _any_ version of MC), though it bugs a bit with Alfheim.

```
>> [23:44:52] [Server thread/ERROR]: Exception caught during firing event cpw.mods.fml.common.gameevent.PlayerEvent$PlayerLoggedInEvent@5d41d099:
>> java.lang.NullPointerException
>> 	at net.minecraftforge.common.BiomeDictionary.isBiomeRegistered(BiomeDictionary.java:267) ~[BiomeDictionary.class:?]
>> 	at net.minecraftforge.common.BiomeDictionary.checkRegistration(BiomeDictionary.java:423) ~[BiomeDictionary.class:?]
>> 	at net.minecraftforge.common.BiomeDictionary.isBiomeOfType(BiomeDictionary.java:250) ~[BiomeDictionary.class:?]
>> 	at com.draco18s.artifacts.worldgen.PlaceTraps.generate(PlaceTraps.java:239) ~[PlaceTraps.class:?]
>> 	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) ~[GameRegistry.class:?]
>> 	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) ~[ms.class:?]
>> 	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1055) ~[apx.class:?]
>> 	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
>> 	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
>> 	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
>> 	at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(PlayerManager.java:509) ~[mr.class:?]
>> 	at net.minecraft.server.management.PlayerManager.getOrCreateChunkWatcher(PlayerManager.java:204) ~[mq.class:?]
>> 	at net.minecraft.server.management.PlayerManager.func_72690_a(PlayerManager.java:194) ~[mq.class:?]
>> 	at net.minecraft.server.management.PlayerManager.func_72683_a(PlayerManager.java:241) ~[mq.class:?]
>> 	at net.minecraft.server.management.ServerConfigurationManager.func_72375_a(ServerConfigurationManager.java:240) ~[oi.class:?]
>> 	at net.minecraft.server.management.ServerConfigurationManager.transferPlayerToDimension(ServerConfigurationManager.java:505) ~[oi.class:?]
>> 	at alexsocol.asjlib.ASJUtilities.sendToDimensionWithoutPortal(ASJUtilities.kt:111) ~[ASJUtilities.class:?]
>> 	at alfheim.common.core.handler.EventHandler.onPlayerLoggedIn(EventHandler.kt:82) ~[EventHandler.class:?]
>> 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_811_EventHandler_onPlayerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
>> 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
>> 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
>> 	at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:550) ~[FMLCommonHandler.class:?]
>> 	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:180) ~[oi.class:?]
>> 	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190) ~[NetworkDispatcher.class:?]
>> 	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:463) ~[NetworkDispatcher.class:?]
>> 	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:17) ~[HandshakeCompletionHandler.class:?]
>> 	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) ~[HandshakeCompletionHandler.class:?]
>> 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
>> 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
>> 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
>> 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
>> 	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
>> 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
>> 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
>> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
>> 	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
>> 	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) ~[FMLProxyPacket.class:?]
>> 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
>> 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
>> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
>> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
>> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186) ~[bsx.class:?]
>> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
>> 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
>> [23:44:52] [Server thread/ERROR]: Index: 29 Listeners:
>> [23:44:52] [Server thread/ERROR]: 0: NORMAL
>> [23:44:52] [Server thread/ERROR]: 1: ASM: Forge playerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 2: ASM: baubles.common.event.EventHandlerNetwork@75950c90 playerLoggedInEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 3: ASM: thaumcraft.common.lib.network.EventHandlerNetwork@6b59e401 playerLoggedInEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 4: ASM: ichun.common.iChunUtil@1b0c34e5 onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 5: ASM: com.enderio.core.common.config.ConfigProcessor@78d3e54c onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 6: ASM: crazypants.enderio.config.Config@77f41d0d onPlayerLoggon(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 7: ASM: crazypants.enderio.machine.hypercube.ConnectionHandler@e7d5315 onPlayerLoggon(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 8: ASM: crazypants.enderio.machine.transceiver.ConnectionHandler@152bee6a onPlayerLoggon(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 9: ASM: com.hbm.main.ModEventHandler@1e0f3714 onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 10: ASM: assets.rivalrebels.common.round.RivalRebelsRound@53def358 onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 11: ASM: sync.common.core.EventHandler@15237784 onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 12: ASM: tconstruct.armor.player.TPlayerHandler@31fda035 PlayerLoggedInEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 13: ASM: codechicken.wirelessredstone.core.WRCoreEventHandler@2a7b137d playerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 14: ASM: com.creativemd.ingameconfigmanager.api.common.event.ConfigEventHandler@7491210 onPlayerJoin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 15: ASM: codechicken.nei.ServerHandler@4b2cb16a loginEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 16: ASM: alfheim.common.core.handler.ragnarok.RagnarokHandler@579f66ca informAboutRagnarok(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 17: ASM: alfheim.common.core.helper.ContributorsPrivacyHelper@21a82bdc onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 18: ASM: twilightforest.TFEventListener@4b962b36 playerLogsIn(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 19: ASM: CoroUtil.forge.EventHandlerFML@72390538 playerLoggedIn(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 20: ASM: mcp.mobius.waila.network.NetworkHandler@4b8380b0 onPlayerLoggedIn(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 21: ASM: thaumic.tinkerer.common.network.PlayerTracker@328c1871 onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 22: ASM: makeo.gadomancy.common.events.EventHandlerNetwork@7887f1a4 on(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 23: ASM: mod_Invasion PlayerLoggedInEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 24: ASM: mapmakingtools.handler.PlayerTrackerHandler@2be2919d login(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 25: ASM: taintedmagic.common.handler.TaintedMagicEventHandler@3e7817ee onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 26: ASM: codechicken.wirelessredstone.addons.WRAddonEventHandler@662ae0e4 playerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 27: ASM: appeng.core.sync.network.NetworkHandler@12690676 newConnection(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
>> [23:44:52] [Server thread/ERROR]: 28: LOWEST
>> [23:44:52] [Server thread/ERROR]: 29: ASM: alfheim.common.core.handler.EventHandler@420d6985 onPlayerLoggedIn(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
```

As we were told by AlexSocol (Alfheim dev), the issue here as follows:

_Alfheim is generated using the World Engine library, which makes the biome in the world as if it were one biome (under one ID), but it has subtypes for landscape diversity. And this biome is not registered in the usual list of biomes. He first takes the biome by coordinates, and then tries to get the same biome, but already from the list of biomes, by its ID. Expectedly, it does not find it, and as a result, an error occurs._

If you'll ever try to make a workaround for this, it would be an amazing thing, as this mod is really great.

**Comment by Draco18s** [comment]
Thanks for reaching out. I'm not able to update this at this time, as I don't have a working dev environment for... uh... I think this was last touched on 1.10?

Anyway, the issue is pretty easy to understand.

This (and other lines like it) need to be adjusted to not reference the biomeID.
https://github.com/Draco18s/Artifacts/blob/master/main/java/com/draco18s/artifacts/worldgen/PlaceTraps.java#L141

Note that I have no fucking idea what line 145 does any more (or rather, why it does it the way it does it). It's clearly a check for specific biomes, but what those ones are, I have no idea, nor what I'd have to do to change the logic around to avoid biome IDs.

And lines like this should just get the current biome and query, like line 84 does:
https://github.com/Draco18s/Artifacts/blob/master/main/java/com/draco18s/artifacts/worldgen/PlaceTraps.java#L153

I'll happily take a pull request with updated code, but I can't build a new jar file.

**Comment by SfortzaPhantom** [comment]
I see, thanks a lot!
